#create_project finn_vivado_stitch_proj /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/vivado_stitch_proj_or5_fmik -part xczu3eg-sbva484-1-i
set_property ip_repo_paths [list /home/nm/FINN/hls_2020_2/finn/finn-rtllib/memstream /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFIFO_0_1d1iqpvt/project_StreamingFIFO_0/sol1/impl/verilog /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_Thresholding_Batch_0_el53y8uf/project_Thresholding_Batch_0/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFIFO_1_b3nja7gg/project_StreamingFIFO_1/sol1/impl/verilog /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_FMPadding_Batch_0_d5f8mhxu/project_FMPadding_Batch_0/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingDataWidthConverter_Batch_0_sh0uf3jl/project_StreamingDataWidthConverter_Batch_0/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFIFO_3_loq_0xkq/project_StreamingFIFO_3/sol1/impl/verilog /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_ConvolutionInputGenerator_0_7ppm_eii/project_ConvolutionInputGenerator_0/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFCLayer_Batch_0_hf84_wbu/project_StreamingFCLayer_Batch_0/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFIFO_5_vo1lrbok/project_StreamingFIFO_5/sol1/impl/verilog /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingMaxPool_Batch_0_vbfstk8e/project_StreamingMaxPool_Batch_0/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFIFO_6_kdsa3i17/project_StreamingFIFO_6/sol1/impl/verilog /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingDataWidthConverter_Batch_1_vl_wwxli/project_StreamingDataWidthConverter_Batch_1/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFIFO_7_jssn2wxj/project_StreamingFIFO_7/sol1/impl/verilog /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_FMPadding_Batch_1_wfqj0zkc/project_FMPadding_Batch_1/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingDataWidthConverter_Batch_2_by2ftyud/project_StreamingDataWidthConverter_Batch_2/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFIFO_9_3axnr8ee/project_StreamingFIFO_9/sol1/impl/verilog /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_ConvolutionInputGenerator_1_n82v_c6i/project_ConvolutionInputGenerator_1/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingDataWidthConverter_Batch_3_5fo4re24/project_StreamingDataWidthConverter_Batch_3/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFIFO_11_b1f0ecpv/project_StreamingFIFO_11/sol1/impl/verilog /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFCLayer_Batch_1_r0htqf01/project_StreamingFCLayer_Batch_1/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingDataWidthConverter_Batch_4_xx9rdve_/project_StreamingDataWidthConverter_Batch_4/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingMaxPool_Batch_1_wfvi1h63/project_StreamingMaxPool_Batch_1/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFIFO_14_vsv3tbf3/project_StreamingFIFO_14/sol1/impl/verilog /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingDataWidthConverter_Batch_5_cox07m1p/project_StreamingDataWidthConverter_Batch_5/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFIFO_15_1qlsll8g/project_StreamingFIFO_15/sol1/impl/verilog /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_FMPadding_Batch_2_stgbwkst/project_FMPadding_Batch_2/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingDataWidthConverter_Batch_6_rk29c15y/project_StreamingDataWidthConverter_Batch_6/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFIFO_17_s43h2lor/project_StreamingFIFO_17/sol1/impl/verilog /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_ConvolutionInputGenerator_2___gsnp1e/project_ConvolutionInputGenerator_2/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingDataWidthConverter_Batch_7_qvf77v5k/project_StreamingDataWidthConverter_Batch_7/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFIFO_19_om7r1lg4/project_StreamingFIFO_19/sol1/impl/verilog /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFCLayer_Batch_2_3rnousoc/project_StreamingFCLayer_Batch_2/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingDataWidthConverter_Batch_8_hg4adyuv/project_StreamingDataWidthConverter_Batch_8/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingMaxPool_Batch_2_as5rwov5/project_StreamingMaxPool_Batch_2/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFIFO_22_ob46z8df/project_StreamingFIFO_22/sol1/impl/verilog /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingDataWidthConverter_Batch_9_a90yoga2/project_StreamingDataWidthConverter_Batch_9/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFIFO_23_hck3mnwr/project_StreamingFIFO_23/sol1/impl/verilog /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_FMPadding_Batch_3_8b4hzha8/project_FMPadding_Batch_3/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingDataWidthConverter_Batch_10_7p64a93_/project_StreamingDataWidthConverter_Batch_10/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFIFO_25_g1vgrklx/project_StreamingFIFO_25/sol1/impl/verilog /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_ConvolutionInputGenerator_3__zochlbb/project_ConvolutionInputGenerator_3/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingDataWidthConverter_Batch_11_x9hc4pvd/project_StreamingDataWidthConverter_Batch_11/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFIFO_27_oi_202_1/project_StreamingFIFO_27/sol1/impl/verilog /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFCLayer_Batch_3_ffmkj9yy/project_StreamingFCLayer_Batch_3/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingDataWidthConverter_Batch_12_ir4icqay/project_StreamingDataWidthConverter_Batch_12/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingMaxPool_Batch_3_rm2f4_jh/project_StreamingMaxPool_Batch_3/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFIFO_30_x1fedh7y/project_StreamingFIFO_30/sol1/impl/verilog /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingDataWidthConverter_Batch_13_2u6rf15r/project_StreamingDataWidthConverter_Batch_13/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFIFO_31_cbxbherd/project_StreamingFIFO_31/sol1/impl/verilog /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_FMPadding_Batch_4_i55jqzgs/project_FMPadding_Batch_4/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFIFO_32_81j6jcow/project_StreamingFIFO_32/sol1/impl/verilog /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_ConvolutionInputGenerator_4_uevjup2f/project_ConvolutionInputGenerator_4/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingDataWidthConverter_Batch_14_6i93q3e5/project_StreamingDataWidthConverter_Batch_14/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFIFO_34_n8s_jxac/project_StreamingFIFO_34/sol1/impl/verilog /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFCLayer_Batch_4_1dot0gc5/project_StreamingFCLayer_Batch_4/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingDataWidthConverter_Batch_15_y3kq6ayl/project_StreamingDataWidthConverter_Batch_15/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingMaxPool_Batch_4_ivooglkb/project_StreamingMaxPool_Batch_4/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFIFO_37_mv229uu1/project_StreamingFIFO_37/sol1/impl/verilog /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingDataWidthConverter_Batch_16_7lnyki26/project_StreamingDataWidthConverter_Batch_16/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFIFO_38_utrcopxg/project_StreamingFIFO_38/sol1/impl/verilog /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_FMPadding_Batch_5_eamodtga/project_FMPadding_Batch_5/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFIFO_39_ench4roj/project_StreamingFIFO_39/sol1/impl/verilog /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_ConvolutionInputGenerator_5__dncufce/project_ConvolutionInputGenerator_5/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingDataWidthConverter_Batch_17_qvna1ydc/project_StreamingDataWidthConverter_Batch_17/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFIFO_41_hdmcplbf/project_StreamingFIFO_41/sol1/impl/verilog /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFCLayer_Batch_5__3j7998n/project_StreamingFCLayer_Batch_5/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingDataWidthConverter_Batch_18_u4n8pq0g/project_StreamingDataWidthConverter_Batch_18/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingMaxPool_Batch_5_l2ns98uu/project_StreamingMaxPool_Batch_5/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingDataWidthConverter_Batch_19_20v2hu0k/project_StreamingDataWidthConverter_Batch_19/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFIFO_45_osd875o9/project_StreamingFIFO_45/sol1/impl/verilog /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_FMPadding_Batch_6_ym0q0aya/project_FMPadding_Batch_6/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFIFO_46_31aeyqiz/project_StreamingFIFO_46/sol1/impl/verilog /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_ConvolutionInputGenerator_6_ydrgsah4/project_ConvolutionInputGenerator_6/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingDataWidthConverter_Batch_20_m4kn_7xm/project_StreamingDataWidthConverter_Batch_20/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFIFO_48_8aob_g7x/project_StreamingFIFO_48/sol1/impl/verilog /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFCLayer_Batch_6_jnwv2iom/project_StreamingFCLayer_Batch_6/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingDataWidthConverter_Batch_21_4wbsqexb/project_StreamingDataWidthConverter_Batch_21/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingMaxPool_Batch_6_boqs8syt/project_StreamingMaxPool_Batch_6/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingDataWidthConverter_Batch_22_itysum2w/project_StreamingDataWidthConverter_Batch_22/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFCLayer_Batch_7_abts7hbd/project_StreamingFCLayer_Batch_7/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingDataWidthConverter_Batch_23_l7opm6zs/project_StreamingDataWidthConverter_Batch_23/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFCLayer_Batch_8_7z6hf082/project_StreamingFCLayer_Batch_8/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingDataWidthConverter_Batch_24_29jb2hyg/project_StreamingDataWidthConverter_Batch_24/sol1/impl/ip /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFCLayer_Batch_9_vfypsnrg/project_StreamingFCLayer_Batch_9/sol1/impl/ip] [current_project]
update_ip_catalog
# create_bd_design "finn_design"
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFIFO_0:1.0 StreamingFIFO_0
create_bd_cell -type ip -vlnv xilinx.com:hls:Thresholding_Batch_0:1.0 Thresholding_Batch_0
create_bd_cell -type hier StreamingFIFO_1
create_bd_pin -dir I -type clk /StreamingFIFO_1/ap_clk
create_bd_pin -dir I -type rst /StreamingFIFO_1/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_1/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_1/in0_V
create_bd_cell -type ip -vlnv xilinx.com:ip:axis_data_fifo:2.0 /StreamingFIFO_1/fifo
set_property -dict [list CONFIG.FIFO_DEPTH {512}] [get_bd_cells /StreamingFIFO_1/fifo]
set_property -dict [list CONFIG.FIFO_MEMORY_TYPE {auto}] [get_bd_cells /StreamingFIFO_1/fifo]
set_property -dict [list CONFIG.TDATA_NUM_BYTES {1}] [get_bd_cells /StreamingFIFO_1/fifo]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_1/fifo/M_AXIS] [get_bd_intf_pins StreamingFIFO_1/out_V]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_1/fifo/S_AXIS] [get_bd_intf_pins StreamingFIFO_1/in0_V]
connect_bd_net [get_bd_pins StreamingFIFO_1/ap_rst_n] [get_bd_pins StreamingFIFO_1/fifo/s_axis_aresetn]
connect_bd_net [get_bd_pins StreamingFIFO_1/ap_clk] [get_bd_pins StreamingFIFO_1/fifo/s_axis_aclk]
create_bd_cell -type ip -vlnv xilinx.com:hls:FMPadding_Batch_0:1.0 FMPadding_Batch_0
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_0:1.0 StreamingDataWidthConverter_Batch_0
create_bd_cell -type hier StreamingFIFO_3
create_bd_pin -dir I -type clk /StreamingFIFO_3/ap_clk
create_bd_pin -dir I -type rst /StreamingFIFO_3/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_3/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_3/in0_V
create_bd_cell -type ip -vlnv xilinx.com:ip:axis_data_fifo:2.0 /StreamingFIFO_3/fifo
set_property -dict [list CONFIG.FIFO_DEPTH {1024}] [get_bd_cells /StreamingFIFO_3/fifo]
set_property -dict [list CONFIG.FIFO_MEMORY_TYPE {auto}] [get_bd_cells /StreamingFIFO_3/fifo]
set_property -dict [list CONFIG.TDATA_NUM_BYTES {3}] [get_bd_cells /StreamingFIFO_3/fifo]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_3/fifo/M_AXIS] [get_bd_intf_pins StreamingFIFO_3/out_V]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_3/fifo/S_AXIS] [get_bd_intf_pins StreamingFIFO_3/in0_V]
connect_bd_net [get_bd_pins StreamingFIFO_3/ap_rst_n] [get_bd_pins StreamingFIFO_3/fifo/s_axis_aresetn]
connect_bd_net [get_bd_pins StreamingFIFO_3/ap_clk] [get_bd_pins StreamingFIFO_3/fifo/s_axis_aclk]
create_bd_cell -type ip -vlnv xilinx.com:hls:ConvolutionInputGenerator_0:1.0 ConvolutionInputGenerator_0
create_bd_cell -type hier StreamingFCLayer_Batch_0
create_bd_pin -dir I -type clk /StreamingFCLayer_Batch_0/ap_clk
create_bd_pin -dir I -type rst /StreamingFCLayer_Batch_0/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFCLayer_Batch_0/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFCLayer_Batch_0/in0_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFCLayer_Batch_0:1.0 /StreamingFCLayer_Batch_0/StreamingFCLayer_Batch_0
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingFCLayer_Batch_0/StreamingFCLayer_Batch_0_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {9} CONFIG.MEM_WIDTH {192} CONFIG.MEM_INIT {/home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFCLayer_Batch_0_hf84_wbu/} CONFIG.RAM_STYLE {distributed} CONFIG.STRM0_DEPTH {9} CONFIG.STRM0_WIDTH {192} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingFCLayer_Batch_0/StreamingFCLayer_Batch_0_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_0/StreamingFCLayer_Batch_0_wstrm/m_axis_0] [get_bd_intf_pins StreamingFCLayer_Batch_0/StreamingFCLayer_Batch_0/weights_V]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_0/ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_0/StreamingFCLayer_Batch_0_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_0/ap_clk] [get_bd_pins StreamingFCLayer_Batch_0/StreamingFCLayer_Batch_0_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_0/ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_0/StreamingFCLayer_Batch_0/ap_rst_n]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_0/ap_clk] [get_bd_pins StreamingFCLayer_Batch_0/StreamingFCLayer_Batch_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_0/in0_V] [get_bd_intf_pins StreamingFCLayer_Batch_0/StreamingFCLayer_Batch_0/in0_V]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_0/out_V] [get_bd_intf_pins StreamingFCLayer_Batch_0/StreamingFCLayer_Batch_0/out_V]
save_bd_design
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFIFO_5:1.0 StreamingFIFO_5
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingMaxPool_Batch_0:1.0 StreamingMaxPool_Batch_0
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFIFO_6:1.0 StreamingFIFO_6
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_1:1.0 StreamingDataWidthConverter_Batch_1
create_bd_cell -type hier StreamingFIFO_7
create_bd_pin -dir I -type clk /StreamingFIFO_7/ap_clk
create_bd_pin -dir I -type rst /StreamingFIFO_7/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_7/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_7/in0_V
create_bd_cell -type ip -vlnv xilinx.com:ip:axis_data_fifo:2.0 /StreamingFIFO_7/fifo
set_property -dict [list CONFIG.FIFO_DEPTH {4096}] [get_bd_cells /StreamingFIFO_7/fifo]
set_property -dict [list CONFIG.FIFO_MEMORY_TYPE {auto}] [get_bd_cells /StreamingFIFO_7/fifo]
set_property -dict [list CONFIG.TDATA_NUM_BYTES {1}] [get_bd_cells /StreamingFIFO_7/fifo]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_7/fifo/M_AXIS] [get_bd_intf_pins StreamingFIFO_7/out_V]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_7/fifo/S_AXIS] [get_bd_intf_pins StreamingFIFO_7/in0_V]
connect_bd_net [get_bd_pins StreamingFIFO_7/ap_rst_n] [get_bd_pins StreamingFIFO_7/fifo/s_axis_aresetn]
connect_bd_net [get_bd_pins StreamingFIFO_7/ap_clk] [get_bd_pins StreamingFIFO_7/fifo/s_axis_aclk]
create_bd_cell -type ip -vlnv xilinx.com:hls:FMPadding_Batch_1:1.0 FMPadding_Batch_1
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_2:1.0 StreamingDataWidthConverter_Batch_2
create_bd_cell -type hier StreamingFIFO_9
create_bd_pin -dir I -type clk /StreamingFIFO_9/ap_clk
create_bd_pin -dir I -type rst /StreamingFIFO_9/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_9/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_9/in0_V
create_bd_cell -type ip -vlnv xilinx.com:ip:axis_data_fifo:2.0 /StreamingFIFO_9/fifo
set_property -dict [list CONFIG.FIFO_DEPTH {2048}] [get_bd_cells /StreamingFIFO_9/fifo]
set_property -dict [list CONFIG.FIFO_MEMORY_TYPE {auto}] [get_bd_cells /StreamingFIFO_9/fifo]
set_property -dict [list CONFIG.TDATA_NUM_BYTES {2}] [get_bd_cells /StreamingFIFO_9/fifo]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_9/fifo/M_AXIS] [get_bd_intf_pins StreamingFIFO_9/out_V]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_9/fifo/S_AXIS] [get_bd_intf_pins StreamingFIFO_9/in0_V]
connect_bd_net [get_bd_pins StreamingFIFO_9/ap_rst_n] [get_bd_pins StreamingFIFO_9/fifo/s_axis_aresetn]
connect_bd_net [get_bd_pins StreamingFIFO_9/ap_clk] [get_bd_pins StreamingFIFO_9/fifo/s_axis_aclk]
create_bd_cell -type ip -vlnv xilinx.com:hls:ConvolutionInputGenerator_1:1.0 ConvolutionInputGenerator_1
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_3:1.0 StreamingDataWidthConverter_Batch_3
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFIFO_11:1.0 StreamingFIFO_11
create_bd_cell -type hier StreamingFCLayer_Batch_1
create_bd_pin -dir I -type clk /StreamingFCLayer_Batch_1/ap_clk
create_bd_pin -dir I -type rst /StreamingFCLayer_Batch_1/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFCLayer_Batch_1/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFCLayer_Batch_1/in0_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFCLayer_Batch_1:1.0 /StreamingFCLayer_Batch_1/StreamingFCLayer_Batch_1
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingFCLayer_Batch_1/StreamingFCLayer_Batch_1_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {36} CONFIG.MEM_WIDTH {1024} CONFIG.MEM_INIT {/home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFCLayer_Batch_1_r0htqf01/} CONFIG.RAM_STYLE {distributed} CONFIG.STRM0_DEPTH {36} CONFIG.STRM0_WIDTH {1024} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingFCLayer_Batch_1/StreamingFCLayer_Batch_1_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_1/StreamingFCLayer_Batch_1_wstrm/m_axis_0] [get_bd_intf_pins StreamingFCLayer_Batch_1/StreamingFCLayer_Batch_1/weights_V]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_1/ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_1/StreamingFCLayer_Batch_1_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_1/ap_clk] [get_bd_pins StreamingFCLayer_Batch_1/StreamingFCLayer_Batch_1_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_1/ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_1/StreamingFCLayer_Batch_1/ap_rst_n]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_1/ap_clk] [get_bd_pins StreamingFCLayer_Batch_1/StreamingFCLayer_Batch_1/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_1/in0_V] [get_bd_intf_pins StreamingFCLayer_Batch_1/StreamingFCLayer_Batch_1/in0_V]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_1/out_V] [get_bd_intf_pins StreamingFCLayer_Batch_1/StreamingFCLayer_Batch_1/out_V]
save_bd_design
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_4:1.0 StreamingDataWidthConverter_Batch_4
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingMaxPool_Batch_1:1.0 StreamingMaxPool_Batch_1
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFIFO_14:1.0 StreamingFIFO_14
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_5:1.0 StreamingDataWidthConverter_Batch_5
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFIFO_15:1.0 StreamingFIFO_15
create_bd_cell -type ip -vlnv xilinx.com:hls:FMPadding_Batch_2:1.0 FMPadding_Batch_2
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_6:1.0 StreamingDataWidthConverter_Batch_6
create_bd_cell -type hier StreamingFIFO_17
create_bd_pin -dir I -type clk /StreamingFIFO_17/ap_clk
create_bd_pin -dir I -type rst /StreamingFIFO_17/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_17/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_17/in0_V
create_bd_cell -type ip -vlnv xilinx.com:ip:axis_data_fifo:2.0 /StreamingFIFO_17/fifo
set_property -dict [list CONFIG.FIFO_DEPTH {4096}] [get_bd_cells /StreamingFIFO_17/fifo]
set_property -dict [list CONFIG.FIFO_MEMORY_TYPE {auto}] [get_bd_cells /StreamingFIFO_17/fifo]
set_property -dict [list CONFIG.TDATA_NUM_BYTES {1}] [get_bd_cells /StreamingFIFO_17/fifo]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_17/fifo/M_AXIS] [get_bd_intf_pins StreamingFIFO_17/out_V]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_17/fifo/S_AXIS] [get_bd_intf_pins StreamingFIFO_17/in0_V]
connect_bd_net [get_bd_pins StreamingFIFO_17/ap_rst_n] [get_bd_pins StreamingFIFO_17/fifo/s_axis_aresetn]
connect_bd_net [get_bd_pins StreamingFIFO_17/ap_clk] [get_bd_pins StreamingFIFO_17/fifo/s_axis_aclk]
create_bd_cell -type ip -vlnv xilinx.com:hls:ConvolutionInputGenerator_2:1.0 ConvolutionInputGenerator_2
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_7:1.0 StreamingDataWidthConverter_Batch_7
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFIFO_19:1.0 StreamingFIFO_19
create_bd_cell -type hier StreamingFCLayer_Batch_2
create_bd_pin -dir I -type clk /StreamingFCLayer_Batch_2/ap_clk
create_bd_pin -dir I -type rst /StreamingFCLayer_Batch_2/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFCLayer_Batch_2/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFCLayer_Batch_2/in0_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFCLayer_Batch_2:1.0 /StreamingFCLayer_Batch_2/StreamingFCLayer_Batch_2
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingFCLayer_Batch_2/StreamingFCLayer_Batch_2_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {144} CONFIG.MEM_WIDTH {512} CONFIG.MEM_INIT {/home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFCLayer_Batch_2_3rnousoc/} CONFIG.RAM_STYLE {distributed} CONFIG.STRM0_DEPTH {144} CONFIG.STRM0_WIDTH {512} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingFCLayer_Batch_2/StreamingFCLayer_Batch_2_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_2/StreamingFCLayer_Batch_2_wstrm/m_axis_0] [get_bd_intf_pins StreamingFCLayer_Batch_2/StreamingFCLayer_Batch_2/weights_V]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_2/ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_2/StreamingFCLayer_Batch_2_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_2/ap_clk] [get_bd_pins StreamingFCLayer_Batch_2/StreamingFCLayer_Batch_2_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_2/ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_2/StreamingFCLayer_Batch_2/ap_rst_n]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_2/ap_clk] [get_bd_pins StreamingFCLayer_Batch_2/StreamingFCLayer_Batch_2/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_2/in0_V] [get_bd_intf_pins StreamingFCLayer_Batch_2/StreamingFCLayer_Batch_2/in0_V]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_2/out_V] [get_bd_intf_pins StreamingFCLayer_Batch_2/StreamingFCLayer_Batch_2/out_V]
save_bd_design
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_8:1.0 StreamingDataWidthConverter_Batch_8
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingMaxPool_Batch_2:1.0 StreamingMaxPool_Batch_2
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFIFO_22:1.0 StreamingFIFO_22
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_9:1.0 StreamingDataWidthConverter_Batch_9
create_bd_cell -type hier StreamingFIFO_23
create_bd_pin -dir I -type clk /StreamingFIFO_23/ap_clk
create_bd_pin -dir I -type rst /StreamingFIFO_23/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_23/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_23/in0_V
create_bd_cell -type ip -vlnv xilinx.com:ip:axis_data_fifo:2.0 /StreamingFIFO_23/fifo
set_property -dict [list CONFIG.FIFO_DEPTH {512}] [get_bd_cells /StreamingFIFO_23/fifo]
set_property -dict [list CONFIG.FIFO_MEMORY_TYPE {auto}] [get_bd_cells /StreamingFIFO_23/fifo]
set_property -dict [list CONFIG.TDATA_NUM_BYTES {1}] [get_bd_cells /StreamingFIFO_23/fifo]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_23/fifo/M_AXIS] [get_bd_intf_pins StreamingFIFO_23/out_V]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_23/fifo/S_AXIS] [get_bd_intf_pins StreamingFIFO_23/in0_V]
connect_bd_net [get_bd_pins StreamingFIFO_23/ap_rst_n] [get_bd_pins StreamingFIFO_23/fifo/s_axis_aresetn]
connect_bd_net [get_bd_pins StreamingFIFO_23/ap_clk] [get_bd_pins StreamingFIFO_23/fifo/s_axis_aclk]
create_bd_cell -type ip -vlnv xilinx.com:hls:FMPadding_Batch_3:1.0 FMPadding_Batch_3
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_10:1.0 StreamingDataWidthConverter_Batch_10
create_bd_cell -type hier StreamingFIFO_25
create_bd_pin -dir I -type clk /StreamingFIFO_25/ap_clk
create_bd_pin -dir I -type rst /StreamingFIFO_25/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_25/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_25/in0_V
create_bd_cell -type ip -vlnv xilinx.com:ip:axis_data_fifo:2.0 /StreamingFIFO_25/fifo
set_property -dict [list CONFIG.FIFO_DEPTH {8192}] [get_bd_cells /StreamingFIFO_25/fifo]
set_property -dict [list CONFIG.FIFO_MEMORY_TYPE {auto}] [get_bd_cells /StreamingFIFO_25/fifo]
set_property -dict [list CONFIG.TDATA_NUM_BYTES {1}] [get_bd_cells /StreamingFIFO_25/fifo]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_25/fifo/M_AXIS] [get_bd_intf_pins StreamingFIFO_25/out_V]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_25/fifo/S_AXIS] [get_bd_intf_pins StreamingFIFO_25/in0_V]
connect_bd_net [get_bd_pins StreamingFIFO_25/ap_rst_n] [get_bd_pins StreamingFIFO_25/fifo/s_axis_aresetn]
connect_bd_net [get_bd_pins StreamingFIFO_25/ap_clk] [get_bd_pins StreamingFIFO_25/fifo/s_axis_aclk]
create_bd_cell -type ip -vlnv xilinx.com:hls:ConvolutionInputGenerator_3:1.0 ConvolutionInputGenerator_3
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_11:1.0 StreamingDataWidthConverter_Batch_11
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFIFO_27:1.0 StreamingFIFO_27
create_bd_cell -type hier StreamingFCLayer_Batch_3
create_bd_pin -dir I -type clk /StreamingFCLayer_Batch_3/ap_clk
create_bd_pin -dir I -type rst /StreamingFCLayer_Batch_3/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFCLayer_Batch_3/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFCLayer_Batch_3/in0_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFCLayer_Batch_3:1.0 /StreamingFCLayer_Batch_3/StreamingFCLayer_Batch_3
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingFCLayer_Batch_3/StreamingFCLayer_Batch_3_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {576} CONFIG.MEM_WIDTH {256} CONFIG.MEM_INIT {/home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFCLayer_Batch_3_ffmkj9yy/} CONFIG.RAM_STYLE {distributed} CONFIG.STRM0_DEPTH {576} CONFIG.STRM0_WIDTH {256} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingFCLayer_Batch_3/StreamingFCLayer_Batch_3_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_3/StreamingFCLayer_Batch_3_wstrm/m_axis_0] [get_bd_intf_pins StreamingFCLayer_Batch_3/StreamingFCLayer_Batch_3/weights_V]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_3/ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_3/StreamingFCLayer_Batch_3_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_3/ap_clk] [get_bd_pins StreamingFCLayer_Batch_3/StreamingFCLayer_Batch_3_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_3/ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_3/StreamingFCLayer_Batch_3/ap_rst_n]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_3/ap_clk] [get_bd_pins StreamingFCLayer_Batch_3/StreamingFCLayer_Batch_3/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_3/in0_V] [get_bd_intf_pins StreamingFCLayer_Batch_3/StreamingFCLayer_Batch_3/in0_V]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_3/out_V] [get_bd_intf_pins StreamingFCLayer_Batch_3/StreamingFCLayer_Batch_3/out_V]
save_bd_design
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_12:1.0 StreamingDataWidthConverter_Batch_12
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingMaxPool_Batch_3:1.0 StreamingMaxPool_Batch_3
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFIFO_30:1.0 StreamingFIFO_30
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_13:1.0 StreamingDataWidthConverter_Batch_13
create_bd_cell -type hier StreamingFIFO_31
create_bd_pin -dir I -type clk /StreamingFIFO_31/ap_clk
create_bd_pin -dir I -type rst /StreamingFIFO_31/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_31/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_31/in0_V
create_bd_cell -type ip -vlnv xilinx.com:ip:axis_data_fifo:2.0 /StreamingFIFO_31/fifo
set_property -dict [list CONFIG.FIFO_DEPTH {512}] [get_bd_cells /StreamingFIFO_31/fifo]
set_property -dict [list CONFIG.FIFO_MEMORY_TYPE {auto}] [get_bd_cells /StreamingFIFO_31/fifo]
set_property -dict [list CONFIG.TDATA_NUM_BYTES {1}] [get_bd_cells /StreamingFIFO_31/fifo]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_31/fifo/M_AXIS] [get_bd_intf_pins StreamingFIFO_31/out_V]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_31/fifo/S_AXIS] [get_bd_intf_pins StreamingFIFO_31/in0_V]
connect_bd_net [get_bd_pins StreamingFIFO_31/ap_rst_n] [get_bd_pins StreamingFIFO_31/fifo/s_axis_aresetn]
connect_bd_net [get_bd_pins StreamingFIFO_31/ap_clk] [get_bd_pins StreamingFIFO_31/fifo/s_axis_aclk]
create_bd_cell -type ip -vlnv xilinx.com:hls:FMPadding_Batch_4:1.0 FMPadding_Batch_4
create_bd_cell -type hier StreamingFIFO_32
create_bd_pin -dir I -type clk /StreamingFIFO_32/ap_clk
create_bd_pin -dir I -type rst /StreamingFIFO_32/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_32/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_32/in0_V
create_bd_cell -type ip -vlnv xilinx.com:ip:axis_data_fifo:2.0 /StreamingFIFO_32/fifo
set_property -dict [list CONFIG.FIFO_DEPTH {8192}] [get_bd_cells /StreamingFIFO_32/fifo]
set_property -dict [list CONFIG.FIFO_MEMORY_TYPE {auto}] [get_bd_cells /StreamingFIFO_32/fifo]
set_property -dict [list CONFIG.TDATA_NUM_BYTES {1}] [get_bd_cells /StreamingFIFO_32/fifo]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_32/fifo/M_AXIS] [get_bd_intf_pins StreamingFIFO_32/out_V]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_32/fifo/S_AXIS] [get_bd_intf_pins StreamingFIFO_32/in0_V]
connect_bd_net [get_bd_pins StreamingFIFO_32/ap_rst_n] [get_bd_pins StreamingFIFO_32/fifo/s_axis_aresetn]
connect_bd_net [get_bd_pins StreamingFIFO_32/ap_clk] [get_bd_pins StreamingFIFO_32/fifo/s_axis_aclk]
create_bd_cell -type ip -vlnv xilinx.com:hls:ConvolutionInputGenerator_4:1.0 ConvolutionInputGenerator_4
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_14:1.0 StreamingDataWidthConverter_Batch_14
create_bd_cell -type hier StreamingFIFO_34
create_bd_pin -dir I -type clk /StreamingFIFO_34/ap_clk
create_bd_pin -dir I -type rst /StreamingFIFO_34/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_34/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_34/in0_V
create_bd_cell -type ip -vlnv xilinx.com:ip:axis_data_fifo:2.0 /StreamingFIFO_34/fifo
set_property -dict [list CONFIG.FIFO_DEPTH {2048}] [get_bd_cells /StreamingFIFO_34/fifo]
set_property -dict [list CONFIG.FIFO_MEMORY_TYPE {auto}] [get_bd_cells /StreamingFIFO_34/fifo]
set_property -dict [list CONFIG.TDATA_NUM_BYTES {4}] [get_bd_cells /StreamingFIFO_34/fifo]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_34/fifo/M_AXIS] [get_bd_intf_pins StreamingFIFO_34/out_V]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_34/fifo/S_AXIS] [get_bd_intf_pins StreamingFIFO_34/in0_V]
connect_bd_net [get_bd_pins StreamingFIFO_34/ap_rst_n] [get_bd_pins StreamingFIFO_34/fifo/s_axis_aresetn]
connect_bd_net [get_bd_pins StreamingFIFO_34/ap_clk] [get_bd_pins StreamingFIFO_34/fifo/s_axis_aclk]
create_bd_cell -type hier StreamingFCLayer_Batch_4
create_bd_pin -dir I -type clk /StreamingFCLayer_Batch_4/ap_clk
create_bd_pin -dir I -type rst /StreamingFCLayer_Batch_4/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFCLayer_Batch_4/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFCLayer_Batch_4/in0_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFCLayer_Batch_4:1.0 /StreamingFCLayer_Batch_4/StreamingFCLayer_Batch_4
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingFCLayer_Batch_4/StreamingFCLayer_Batch_4_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {2304} CONFIG.MEM_WIDTH {128} CONFIG.MEM_INIT {/home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFCLayer_Batch_4_1dot0gc5/} CONFIG.RAM_STYLE {distributed} CONFIG.STRM0_DEPTH {2304} CONFIG.STRM0_WIDTH {128} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingFCLayer_Batch_4/StreamingFCLayer_Batch_4_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_4/StreamingFCLayer_Batch_4_wstrm/m_axis_0] [get_bd_intf_pins StreamingFCLayer_Batch_4/StreamingFCLayer_Batch_4/weights_V]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_4/ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_4/StreamingFCLayer_Batch_4_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_4/ap_clk] [get_bd_pins StreamingFCLayer_Batch_4/StreamingFCLayer_Batch_4_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_4/ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_4/StreamingFCLayer_Batch_4/ap_rst_n]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_4/ap_clk] [get_bd_pins StreamingFCLayer_Batch_4/StreamingFCLayer_Batch_4/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_4/in0_V] [get_bd_intf_pins StreamingFCLayer_Batch_4/StreamingFCLayer_Batch_4/in0_V]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_4/out_V] [get_bd_intf_pins StreamingFCLayer_Batch_4/StreamingFCLayer_Batch_4/out_V]
save_bd_design
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_15:1.0 StreamingDataWidthConverter_Batch_15
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingMaxPool_Batch_4:1.0 StreamingMaxPool_Batch_4
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFIFO_37:1.0 StreamingFIFO_37
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_16:1.0 StreamingDataWidthConverter_Batch_16
create_bd_cell -type hier StreamingFIFO_38
create_bd_pin -dir I -type clk /StreamingFIFO_38/ap_clk
create_bd_pin -dir I -type rst /StreamingFIFO_38/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_38/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_38/in0_V
create_bd_cell -type ip -vlnv xilinx.com:ip:axis_data_fifo:2.0 /StreamingFIFO_38/fifo
set_property -dict [list CONFIG.FIFO_DEPTH {1024}] [get_bd_cells /StreamingFIFO_38/fifo]
set_property -dict [list CONFIG.FIFO_MEMORY_TYPE {auto}] [get_bd_cells /StreamingFIFO_38/fifo]
set_property -dict [list CONFIG.TDATA_NUM_BYTES {1}] [get_bd_cells /StreamingFIFO_38/fifo]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_38/fifo/M_AXIS] [get_bd_intf_pins StreamingFIFO_38/out_V]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_38/fifo/S_AXIS] [get_bd_intf_pins StreamingFIFO_38/in0_V]
connect_bd_net [get_bd_pins StreamingFIFO_38/ap_rst_n] [get_bd_pins StreamingFIFO_38/fifo/s_axis_aresetn]
connect_bd_net [get_bd_pins StreamingFIFO_38/ap_clk] [get_bd_pins StreamingFIFO_38/fifo/s_axis_aclk]
create_bd_cell -type ip -vlnv xilinx.com:hls:FMPadding_Batch_5:1.0 FMPadding_Batch_5
create_bd_cell -type hier StreamingFIFO_39
create_bd_pin -dir I -type clk /StreamingFIFO_39/ap_clk
create_bd_pin -dir I -type rst /StreamingFIFO_39/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_39/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_39/in0_V
create_bd_cell -type ip -vlnv xilinx.com:ip:axis_data_fifo:2.0 /StreamingFIFO_39/fifo
set_property -dict [list CONFIG.FIFO_DEPTH {8192}] [get_bd_cells /StreamingFIFO_39/fifo]
set_property -dict [list CONFIG.FIFO_MEMORY_TYPE {auto}] [get_bd_cells /StreamingFIFO_39/fifo]
set_property -dict [list CONFIG.TDATA_NUM_BYTES {1}] [get_bd_cells /StreamingFIFO_39/fifo]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_39/fifo/M_AXIS] [get_bd_intf_pins StreamingFIFO_39/out_V]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_39/fifo/S_AXIS] [get_bd_intf_pins StreamingFIFO_39/in0_V]
connect_bd_net [get_bd_pins StreamingFIFO_39/ap_rst_n] [get_bd_pins StreamingFIFO_39/fifo/s_axis_aresetn]
connect_bd_net [get_bd_pins StreamingFIFO_39/ap_clk] [get_bd_pins StreamingFIFO_39/fifo/s_axis_aclk]
create_bd_cell -type ip -vlnv xilinx.com:hls:ConvolutionInputGenerator_5:1.0 ConvolutionInputGenerator_5
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_17:1.0 StreamingDataWidthConverter_Batch_17
create_bd_cell -type hier StreamingFIFO_41
create_bd_pin -dir I -type clk /StreamingFIFO_41/ap_clk
create_bd_pin -dir I -type rst /StreamingFIFO_41/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_41/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_41/in0_V
create_bd_cell -type ip -vlnv xilinx.com:ip:axis_data_fifo:2.0 /StreamingFIFO_41/fifo
set_property -dict [list CONFIG.FIFO_DEPTH {2048}] [get_bd_cells /StreamingFIFO_41/fifo]
set_property -dict [list CONFIG.FIFO_MEMORY_TYPE {auto}] [get_bd_cells /StreamingFIFO_41/fifo]
set_property -dict [list CONFIG.TDATA_NUM_BYTES {4}] [get_bd_cells /StreamingFIFO_41/fifo]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_41/fifo/M_AXIS] [get_bd_intf_pins StreamingFIFO_41/out_V]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_41/fifo/S_AXIS] [get_bd_intf_pins StreamingFIFO_41/in0_V]
connect_bd_net [get_bd_pins StreamingFIFO_41/ap_rst_n] [get_bd_pins StreamingFIFO_41/fifo/s_axis_aresetn]
connect_bd_net [get_bd_pins StreamingFIFO_41/ap_clk] [get_bd_pins StreamingFIFO_41/fifo/s_axis_aclk]
create_bd_cell -type hier StreamingFCLayer_Batch_5
create_bd_pin -dir I -type clk /StreamingFCLayer_Batch_5/ap_clk
create_bd_pin -dir I -type rst /StreamingFCLayer_Batch_5/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFCLayer_Batch_5/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFCLayer_Batch_5/in0_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFCLayer_Batch_5:1.0 /StreamingFCLayer_Batch_5/StreamingFCLayer_Batch_5
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingFCLayer_Batch_5/StreamingFCLayer_Batch_5_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {9216} CONFIG.MEM_WIDTH {64} CONFIG.MEM_INIT {/home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFCLayer_Batch_5__3j7998n/} CONFIG.RAM_STYLE {distributed} CONFIG.STRM0_DEPTH {9216} CONFIG.STRM0_WIDTH {64} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingFCLayer_Batch_5/StreamingFCLayer_Batch_5_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_5/StreamingFCLayer_Batch_5_wstrm/m_axis_0] [get_bd_intf_pins StreamingFCLayer_Batch_5/StreamingFCLayer_Batch_5/weights_V]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_5/ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_5/StreamingFCLayer_Batch_5_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_5/ap_clk] [get_bd_pins StreamingFCLayer_Batch_5/StreamingFCLayer_Batch_5_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_5/ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_5/StreamingFCLayer_Batch_5/ap_rst_n]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_5/ap_clk] [get_bd_pins StreamingFCLayer_Batch_5/StreamingFCLayer_Batch_5/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_5/in0_V] [get_bd_intf_pins StreamingFCLayer_Batch_5/StreamingFCLayer_Batch_5/in0_V]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_5/out_V] [get_bd_intf_pins StreamingFCLayer_Batch_5/StreamingFCLayer_Batch_5/out_V]
save_bd_design
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_18:1.0 StreamingDataWidthConverter_Batch_18
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingMaxPool_Batch_5:1.0 StreamingMaxPool_Batch_5
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_19:1.0 StreamingDataWidthConverter_Batch_19
create_bd_cell -type hier StreamingFIFO_45
create_bd_pin -dir I -type clk /StreamingFIFO_45/ap_clk
create_bd_pin -dir I -type rst /StreamingFIFO_45/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_45/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_45/in0_V
create_bd_cell -type ip -vlnv xilinx.com:ip:axis_data_fifo:2.0 /StreamingFIFO_45/fifo
set_property -dict [list CONFIG.FIFO_DEPTH {1024}] [get_bd_cells /StreamingFIFO_45/fifo]
set_property -dict [list CONFIG.FIFO_MEMORY_TYPE {auto}] [get_bd_cells /StreamingFIFO_45/fifo]
set_property -dict [list CONFIG.TDATA_NUM_BYTES {1}] [get_bd_cells /StreamingFIFO_45/fifo]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_45/fifo/M_AXIS] [get_bd_intf_pins StreamingFIFO_45/out_V]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_45/fifo/S_AXIS] [get_bd_intf_pins StreamingFIFO_45/in0_V]
connect_bd_net [get_bd_pins StreamingFIFO_45/ap_rst_n] [get_bd_pins StreamingFIFO_45/fifo/s_axis_aresetn]
connect_bd_net [get_bd_pins StreamingFIFO_45/ap_clk] [get_bd_pins StreamingFIFO_45/fifo/s_axis_aclk]
create_bd_cell -type ip -vlnv xilinx.com:hls:FMPadding_Batch_6:1.0 FMPadding_Batch_6
create_bd_cell -type hier StreamingFIFO_46
create_bd_pin -dir I -type clk /StreamingFIFO_46/ap_clk
create_bd_pin -dir I -type rst /StreamingFIFO_46/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_46/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_46/in0_V
create_bd_cell -type ip -vlnv xilinx.com:ip:axis_data_fifo:2.0 /StreamingFIFO_46/fifo
set_property -dict [list CONFIG.FIFO_DEPTH {8192}] [get_bd_cells /StreamingFIFO_46/fifo]
set_property -dict [list CONFIG.FIFO_MEMORY_TYPE {auto}] [get_bd_cells /StreamingFIFO_46/fifo]
set_property -dict [list CONFIG.TDATA_NUM_BYTES {1}] [get_bd_cells /StreamingFIFO_46/fifo]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_46/fifo/M_AXIS] [get_bd_intf_pins StreamingFIFO_46/out_V]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_46/fifo/S_AXIS] [get_bd_intf_pins StreamingFIFO_46/in0_V]
connect_bd_net [get_bd_pins StreamingFIFO_46/ap_rst_n] [get_bd_pins StreamingFIFO_46/fifo/s_axis_aresetn]
connect_bd_net [get_bd_pins StreamingFIFO_46/ap_clk] [get_bd_pins StreamingFIFO_46/fifo/s_axis_aclk]
create_bd_cell -type ip -vlnv xilinx.com:hls:ConvolutionInputGenerator_6:1.0 ConvolutionInputGenerator_6
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_20:1.0 StreamingDataWidthConverter_Batch_20
create_bd_cell -type hier StreamingFIFO_48
create_bd_pin -dir I -type clk /StreamingFIFO_48/ap_clk
create_bd_pin -dir I -type rst /StreamingFIFO_48/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_48/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFIFO_48/in0_V
create_bd_cell -type ip -vlnv xilinx.com:ip:axis_data_fifo:2.0 /StreamingFIFO_48/fifo
set_property -dict [list CONFIG.FIFO_DEPTH {1024}] [get_bd_cells /StreamingFIFO_48/fifo]
set_property -dict [list CONFIG.FIFO_MEMORY_TYPE {auto}] [get_bd_cells /StreamingFIFO_48/fifo]
set_property -dict [list CONFIG.TDATA_NUM_BYTES {4}] [get_bd_cells /StreamingFIFO_48/fifo]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_48/fifo/M_AXIS] [get_bd_intf_pins StreamingFIFO_48/out_V]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_48/fifo/S_AXIS] [get_bd_intf_pins StreamingFIFO_48/in0_V]
connect_bd_net [get_bd_pins StreamingFIFO_48/ap_rst_n] [get_bd_pins StreamingFIFO_48/fifo/s_axis_aresetn]
connect_bd_net [get_bd_pins StreamingFIFO_48/ap_clk] [get_bd_pins StreamingFIFO_48/fifo/s_axis_aclk]
create_bd_cell -type hier StreamingFCLayer_Batch_6
create_bd_pin -dir I -type clk /StreamingFCLayer_Batch_6/ap_clk
create_bd_pin -dir I -type rst /StreamingFCLayer_Batch_6/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFCLayer_Batch_6/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFCLayer_Batch_6/in0_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFCLayer_Batch_6:1.0 /StreamingFCLayer_Batch_6/StreamingFCLayer_Batch_6
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingFCLayer_Batch_6/StreamingFCLayer_Batch_6_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {18432} CONFIG.MEM_WIDTH {32} CONFIG.MEM_INIT {/home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFCLayer_Batch_6_jnwv2iom/} CONFIG.RAM_STYLE {block} CONFIG.STRM0_DEPTH {18432} CONFIG.STRM0_WIDTH {32} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingFCLayer_Batch_6/StreamingFCLayer_Batch_6_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_6/StreamingFCLayer_Batch_6_wstrm/m_axis_0] [get_bd_intf_pins StreamingFCLayer_Batch_6/StreamingFCLayer_Batch_6/weights_V]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_6/ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_6/StreamingFCLayer_Batch_6_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_6/ap_clk] [get_bd_pins StreamingFCLayer_Batch_6/StreamingFCLayer_Batch_6_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_6/ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_6/StreamingFCLayer_Batch_6/ap_rst_n]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_6/ap_clk] [get_bd_pins StreamingFCLayer_Batch_6/StreamingFCLayer_Batch_6/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_6/in0_V] [get_bd_intf_pins StreamingFCLayer_Batch_6/StreamingFCLayer_Batch_6/in0_V]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_6/out_V] [get_bd_intf_pins StreamingFCLayer_Batch_6/StreamingFCLayer_Batch_6/out_V]
save_bd_design
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_21:1.0 StreamingDataWidthConverter_Batch_21
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingMaxPool_Batch_6:1.0 StreamingMaxPool_Batch_6
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_22:1.0 StreamingDataWidthConverter_Batch_22
create_bd_cell -type hier StreamingFCLayer_Batch_7
create_bd_pin -dir I -type clk /StreamingFCLayer_Batch_7/ap_clk
create_bd_pin -dir I -type rst /StreamingFCLayer_Batch_7/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFCLayer_Batch_7/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFCLayer_Batch_7/in0_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFCLayer_Batch_7:1.0 /StreamingFCLayer_Batch_7/StreamingFCLayer_Batch_7
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingFCLayer_Batch_7/StreamingFCLayer_Batch_7_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {65536} CONFIG.MEM_WIDTH {8} CONFIG.MEM_INIT {/home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFCLayer_Batch_7_abts7hbd/} CONFIG.RAM_STYLE {block} CONFIG.STRM0_DEPTH {65536} CONFIG.STRM0_WIDTH {8} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingFCLayer_Batch_7/StreamingFCLayer_Batch_7_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_7/StreamingFCLayer_Batch_7_wstrm/m_axis_0] [get_bd_intf_pins StreamingFCLayer_Batch_7/StreamingFCLayer_Batch_7/weights_V]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_7/ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_7/StreamingFCLayer_Batch_7_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_7/ap_clk] [get_bd_pins StreamingFCLayer_Batch_7/StreamingFCLayer_Batch_7_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_7/ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_7/StreamingFCLayer_Batch_7/ap_rst_n]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_7/ap_clk] [get_bd_pins StreamingFCLayer_Batch_7/StreamingFCLayer_Batch_7/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_7/in0_V] [get_bd_intf_pins StreamingFCLayer_Batch_7/StreamingFCLayer_Batch_7/in0_V]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_7/out_V] [get_bd_intf_pins StreamingFCLayer_Batch_7/StreamingFCLayer_Batch_7/out_V]
save_bd_design
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_23:1.0 StreamingDataWidthConverter_Batch_23
create_bd_cell -type hier StreamingFCLayer_Batch_8
create_bd_pin -dir I -type clk /StreamingFCLayer_Batch_8/ap_clk
create_bd_pin -dir I -type rst /StreamingFCLayer_Batch_8/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFCLayer_Batch_8/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFCLayer_Batch_8/in0_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFCLayer_Batch_8:1.0 /StreamingFCLayer_Batch_8/StreamingFCLayer_Batch_8
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingFCLayer_Batch_8/StreamingFCLayer_Batch_8_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {8192} CONFIG.MEM_WIDTH {8} CONFIG.MEM_INIT {/home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFCLayer_Batch_8_7z6hf082/} CONFIG.RAM_STYLE {block} CONFIG.STRM0_DEPTH {8192} CONFIG.STRM0_WIDTH {8} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingFCLayer_Batch_8/StreamingFCLayer_Batch_8_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_8/StreamingFCLayer_Batch_8_wstrm/m_axis_0] [get_bd_intf_pins StreamingFCLayer_Batch_8/StreamingFCLayer_Batch_8/weights_V]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_8/ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_8/StreamingFCLayer_Batch_8_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_8/ap_clk] [get_bd_pins StreamingFCLayer_Batch_8/StreamingFCLayer_Batch_8_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_8/ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_8/StreamingFCLayer_Batch_8/ap_rst_n]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_8/ap_clk] [get_bd_pins StreamingFCLayer_Batch_8/StreamingFCLayer_Batch_8/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_8/in0_V] [get_bd_intf_pins StreamingFCLayer_Batch_8/StreamingFCLayer_Batch_8/in0_V]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_8/out_V] [get_bd_intf_pins StreamingFCLayer_Batch_8/StreamingFCLayer_Batch_8/out_V]
save_bd_design
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_24:1.0 StreamingDataWidthConverter_Batch_24
create_bd_cell -type hier StreamingFCLayer_Batch_9
create_bd_pin -dir I -type clk /StreamingFCLayer_Batch_9/ap_clk
create_bd_pin -dir I -type rst /StreamingFCLayer_Batch_9/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFCLayer_Batch_9/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingFCLayer_Batch_9/in0_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFCLayer_Batch_9:1.0 /StreamingFCLayer_Batch_9/StreamingFCLayer_Batch_9
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingFCLayer_Batch_9/StreamingFCLayer_Batch_9_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {64} CONFIG.MEM_WIDTH {16} CONFIG.MEM_INIT {/home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/code_gen_ipgen_StreamingFCLayer_Batch_9_vfypsnrg/} CONFIG.RAM_STYLE {block} CONFIG.STRM0_DEPTH {64} CONFIG.STRM0_WIDTH {16} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingFCLayer_Batch_9/StreamingFCLayer_Batch_9_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_9/StreamingFCLayer_Batch_9_wstrm/m_axis_0] [get_bd_intf_pins StreamingFCLayer_Batch_9/StreamingFCLayer_Batch_9/weights_V]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_9/ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_9/StreamingFCLayer_Batch_9_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_9/ap_clk] [get_bd_pins StreamingFCLayer_Batch_9/StreamingFCLayer_Batch_9_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_9/ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_9/StreamingFCLayer_Batch_9/ap_rst_n]
connect_bd_net [get_bd_pins StreamingFCLayer_Batch_9/ap_clk] [get_bd_pins StreamingFCLayer_Batch_9/StreamingFCLayer_Batch_9/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_9/in0_V] [get_bd_intf_pins StreamingFCLayer_Batch_9/StreamingFCLayer_Batch_9/in0_V]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_9/out_V] [get_bd_intf_pins StreamingFCLayer_Batch_9/StreamingFCLayer_Batch_9/out_V]
save_bd_design
make_bd_pins_external [get_bd_pins StreamingFIFO_0/ap_clk]
set_property name ap_clk [get_bd_ports ap_clk_0]
make_bd_pins_external [get_bd_pins StreamingFIFO_0/ap_rst_n]
set_property name ap_rst_n [get_bd_ports ap_rst_n_0]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins Thresholding_Batch_0/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins Thresholding_Batch_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_0/out_V] [get_bd_intf_pins Thresholding_Batch_0/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFIFO_1/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFIFO_1/ap_clk]
connect_bd_intf_net [get_bd_intf_pins Thresholding_Batch_0/out_V] [get_bd_intf_pins StreamingFIFO_1/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins FMPadding_Batch_0/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins FMPadding_Batch_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_1/out_V] [get_bd_intf_pins FMPadding_Batch_0/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataWidthConverter_Batch_0/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataWidthConverter_Batch_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins FMPadding_Batch_0/out_V] [get_bd_intf_pins StreamingDataWidthConverter_Batch_0/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFIFO_3/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFIFO_3/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataWidthConverter_Batch_0/out_V] [get_bd_intf_pins StreamingFIFO_3/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins ConvolutionInputGenerator_0/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins ConvolutionInputGenerator_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_3/out_V] [get_bd_intf_pins ConvolutionInputGenerator_0/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_0/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFCLayer_Batch_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins ConvolutionInputGenerator_0/out_V] [get_bd_intf_pins StreamingFCLayer_Batch_0/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFIFO_5/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFIFO_5/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_0/out_V] [get_bd_intf_pins StreamingFIFO_5/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingMaxPool_Batch_0/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingMaxPool_Batch_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_5/out_V] [get_bd_intf_pins StreamingMaxPool_Batch_0/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFIFO_6/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFIFO_6/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingMaxPool_Batch_0/out_V] [get_bd_intf_pins StreamingFIFO_6/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataWidthConverter_Batch_1/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataWidthConverter_Batch_1/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_6/out_V] [get_bd_intf_pins StreamingDataWidthConverter_Batch_1/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFIFO_7/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFIFO_7/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataWidthConverter_Batch_1/out_V] [get_bd_intf_pins StreamingFIFO_7/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins FMPadding_Batch_1/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins FMPadding_Batch_1/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_7/out_V] [get_bd_intf_pins FMPadding_Batch_1/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataWidthConverter_Batch_2/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataWidthConverter_Batch_2/ap_clk]
connect_bd_intf_net [get_bd_intf_pins FMPadding_Batch_1/out_V] [get_bd_intf_pins StreamingDataWidthConverter_Batch_2/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFIFO_9/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFIFO_9/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataWidthConverter_Batch_2/out_V] [get_bd_intf_pins StreamingFIFO_9/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins ConvolutionInputGenerator_1/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins ConvolutionInputGenerator_1/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_9/out_V] [get_bd_intf_pins ConvolutionInputGenerator_1/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataWidthConverter_Batch_3/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataWidthConverter_Batch_3/ap_clk]
connect_bd_intf_net [get_bd_intf_pins ConvolutionInputGenerator_1/out_V] [get_bd_intf_pins StreamingDataWidthConverter_Batch_3/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFIFO_11/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFIFO_11/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataWidthConverter_Batch_3/out_V] [get_bd_intf_pins StreamingFIFO_11/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_1/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFCLayer_Batch_1/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_11/out_V] [get_bd_intf_pins StreamingFCLayer_Batch_1/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataWidthConverter_Batch_4/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataWidthConverter_Batch_4/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_1/out_V] [get_bd_intf_pins StreamingDataWidthConverter_Batch_4/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingMaxPool_Batch_1/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingMaxPool_Batch_1/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataWidthConverter_Batch_4/out_V] [get_bd_intf_pins StreamingMaxPool_Batch_1/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFIFO_14/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFIFO_14/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingMaxPool_Batch_1/out_V] [get_bd_intf_pins StreamingFIFO_14/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataWidthConverter_Batch_5/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataWidthConverter_Batch_5/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_14/out_V] [get_bd_intf_pins StreamingDataWidthConverter_Batch_5/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFIFO_15/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFIFO_15/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataWidthConverter_Batch_5/out_V] [get_bd_intf_pins StreamingFIFO_15/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins FMPadding_Batch_2/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins FMPadding_Batch_2/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_15/out_V] [get_bd_intf_pins FMPadding_Batch_2/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataWidthConverter_Batch_6/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataWidthConverter_Batch_6/ap_clk]
connect_bd_intf_net [get_bd_intf_pins FMPadding_Batch_2/out_V] [get_bd_intf_pins StreamingDataWidthConverter_Batch_6/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFIFO_17/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFIFO_17/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataWidthConverter_Batch_6/out_V] [get_bd_intf_pins StreamingFIFO_17/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins ConvolutionInputGenerator_2/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins ConvolutionInputGenerator_2/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_17/out_V] [get_bd_intf_pins ConvolutionInputGenerator_2/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataWidthConverter_Batch_7/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataWidthConverter_Batch_7/ap_clk]
connect_bd_intf_net [get_bd_intf_pins ConvolutionInputGenerator_2/out_V] [get_bd_intf_pins StreamingDataWidthConverter_Batch_7/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFIFO_19/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFIFO_19/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataWidthConverter_Batch_7/out_V] [get_bd_intf_pins StreamingFIFO_19/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_2/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFCLayer_Batch_2/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_19/out_V] [get_bd_intf_pins StreamingFCLayer_Batch_2/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataWidthConverter_Batch_8/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataWidthConverter_Batch_8/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_2/out_V] [get_bd_intf_pins StreamingDataWidthConverter_Batch_8/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingMaxPool_Batch_2/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingMaxPool_Batch_2/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataWidthConverter_Batch_8/out_V] [get_bd_intf_pins StreamingMaxPool_Batch_2/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFIFO_22/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFIFO_22/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingMaxPool_Batch_2/out_V] [get_bd_intf_pins StreamingFIFO_22/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataWidthConverter_Batch_9/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataWidthConverter_Batch_9/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_22/out_V] [get_bd_intf_pins StreamingDataWidthConverter_Batch_9/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFIFO_23/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFIFO_23/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataWidthConverter_Batch_9/out_V] [get_bd_intf_pins StreamingFIFO_23/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins FMPadding_Batch_3/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins FMPadding_Batch_3/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_23/out_V] [get_bd_intf_pins FMPadding_Batch_3/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataWidthConverter_Batch_10/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataWidthConverter_Batch_10/ap_clk]
connect_bd_intf_net [get_bd_intf_pins FMPadding_Batch_3/out_V] [get_bd_intf_pins StreamingDataWidthConverter_Batch_10/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFIFO_25/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFIFO_25/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataWidthConverter_Batch_10/out_V] [get_bd_intf_pins StreamingFIFO_25/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins ConvolutionInputGenerator_3/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins ConvolutionInputGenerator_3/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_25/out_V] [get_bd_intf_pins ConvolutionInputGenerator_3/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataWidthConverter_Batch_11/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataWidthConverter_Batch_11/ap_clk]
connect_bd_intf_net [get_bd_intf_pins ConvolutionInputGenerator_3/out_V] [get_bd_intf_pins StreamingDataWidthConverter_Batch_11/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFIFO_27/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFIFO_27/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataWidthConverter_Batch_11/out_V] [get_bd_intf_pins StreamingFIFO_27/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_3/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFCLayer_Batch_3/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_27/out_V] [get_bd_intf_pins StreamingFCLayer_Batch_3/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataWidthConverter_Batch_12/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataWidthConverter_Batch_12/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_3/out_V] [get_bd_intf_pins StreamingDataWidthConverter_Batch_12/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingMaxPool_Batch_3/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingMaxPool_Batch_3/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataWidthConverter_Batch_12/out_V] [get_bd_intf_pins StreamingMaxPool_Batch_3/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFIFO_30/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFIFO_30/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingMaxPool_Batch_3/out_V] [get_bd_intf_pins StreamingFIFO_30/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataWidthConverter_Batch_13/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataWidthConverter_Batch_13/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_30/out_V] [get_bd_intf_pins StreamingDataWidthConverter_Batch_13/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFIFO_31/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFIFO_31/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataWidthConverter_Batch_13/out_V] [get_bd_intf_pins StreamingFIFO_31/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins FMPadding_Batch_4/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins FMPadding_Batch_4/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_31/out_V] [get_bd_intf_pins FMPadding_Batch_4/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFIFO_32/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFIFO_32/ap_clk]
connect_bd_intf_net [get_bd_intf_pins FMPadding_Batch_4/out_V] [get_bd_intf_pins StreamingFIFO_32/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins ConvolutionInputGenerator_4/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins ConvolutionInputGenerator_4/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_32/out_V] [get_bd_intf_pins ConvolutionInputGenerator_4/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataWidthConverter_Batch_14/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataWidthConverter_Batch_14/ap_clk]
connect_bd_intf_net [get_bd_intf_pins ConvolutionInputGenerator_4/out_V] [get_bd_intf_pins StreamingDataWidthConverter_Batch_14/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFIFO_34/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFIFO_34/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataWidthConverter_Batch_14/out_V] [get_bd_intf_pins StreamingFIFO_34/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_4/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFCLayer_Batch_4/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_34/out_V] [get_bd_intf_pins StreamingFCLayer_Batch_4/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataWidthConverter_Batch_15/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataWidthConverter_Batch_15/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_4/out_V] [get_bd_intf_pins StreamingDataWidthConverter_Batch_15/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingMaxPool_Batch_4/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingMaxPool_Batch_4/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataWidthConverter_Batch_15/out_V] [get_bd_intf_pins StreamingMaxPool_Batch_4/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFIFO_37/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFIFO_37/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingMaxPool_Batch_4/out_V] [get_bd_intf_pins StreamingFIFO_37/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataWidthConverter_Batch_16/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataWidthConverter_Batch_16/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_37/out_V] [get_bd_intf_pins StreamingDataWidthConverter_Batch_16/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFIFO_38/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFIFO_38/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataWidthConverter_Batch_16/out_V] [get_bd_intf_pins StreamingFIFO_38/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins FMPadding_Batch_5/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins FMPadding_Batch_5/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_38/out_V] [get_bd_intf_pins FMPadding_Batch_5/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFIFO_39/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFIFO_39/ap_clk]
connect_bd_intf_net [get_bd_intf_pins FMPadding_Batch_5/out_V] [get_bd_intf_pins StreamingFIFO_39/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins ConvolutionInputGenerator_5/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins ConvolutionInputGenerator_5/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_39/out_V] [get_bd_intf_pins ConvolutionInputGenerator_5/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataWidthConverter_Batch_17/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataWidthConverter_Batch_17/ap_clk]
connect_bd_intf_net [get_bd_intf_pins ConvolutionInputGenerator_5/out_V] [get_bd_intf_pins StreamingDataWidthConverter_Batch_17/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFIFO_41/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFIFO_41/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataWidthConverter_Batch_17/out_V] [get_bd_intf_pins StreamingFIFO_41/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_5/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFCLayer_Batch_5/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_41/out_V] [get_bd_intf_pins StreamingFCLayer_Batch_5/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataWidthConverter_Batch_18/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataWidthConverter_Batch_18/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_5/out_V] [get_bd_intf_pins StreamingDataWidthConverter_Batch_18/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingMaxPool_Batch_5/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingMaxPool_Batch_5/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataWidthConverter_Batch_18/out_V] [get_bd_intf_pins StreamingMaxPool_Batch_5/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataWidthConverter_Batch_19/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataWidthConverter_Batch_19/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingMaxPool_Batch_5/out_V] [get_bd_intf_pins StreamingDataWidthConverter_Batch_19/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFIFO_45/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFIFO_45/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataWidthConverter_Batch_19/out_V] [get_bd_intf_pins StreamingFIFO_45/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins FMPadding_Batch_6/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins FMPadding_Batch_6/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_45/out_V] [get_bd_intf_pins FMPadding_Batch_6/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFIFO_46/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFIFO_46/ap_clk]
connect_bd_intf_net [get_bd_intf_pins FMPadding_Batch_6/out_V] [get_bd_intf_pins StreamingFIFO_46/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins ConvolutionInputGenerator_6/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins ConvolutionInputGenerator_6/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_46/out_V] [get_bd_intf_pins ConvolutionInputGenerator_6/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataWidthConverter_Batch_20/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataWidthConverter_Batch_20/ap_clk]
connect_bd_intf_net [get_bd_intf_pins ConvolutionInputGenerator_6/out_V] [get_bd_intf_pins StreamingDataWidthConverter_Batch_20/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFIFO_48/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFIFO_48/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataWidthConverter_Batch_20/out_V] [get_bd_intf_pins StreamingFIFO_48/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_6/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFCLayer_Batch_6/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFIFO_48/out_V] [get_bd_intf_pins StreamingFCLayer_Batch_6/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataWidthConverter_Batch_21/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataWidthConverter_Batch_21/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_6/out_V] [get_bd_intf_pins StreamingDataWidthConverter_Batch_21/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingMaxPool_Batch_6/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingMaxPool_Batch_6/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataWidthConverter_Batch_21/out_V] [get_bd_intf_pins StreamingMaxPool_Batch_6/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataWidthConverter_Batch_22/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataWidthConverter_Batch_22/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingMaxPool_Batch_6/out_V] [get_bd_intf_pins StreamingDataWidthConverter_Batch_22/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_7/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFCLayer_Batch_7/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataWidthConverter_Batch_22/out_V] [get_bd_intf_pins StreamingFCLayer_Batch_7/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataWidthConverter_Batch_23/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataWidthConverter_Batch_23/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_7/out_V] [get_bd_intf_pins StreamingDataWidthConverter_Batch_23/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_8/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFCLayer_Batch_8/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataWidthConverter_Batch_23/out_V] [get_bd_intf_pins StreamingFCLayer_Batch_8/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataWidthConverter_Batch_24/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataWidthConverter_Batch_24/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingFCLayer_Batch_8/out_V] [get_bd_intf_pins StreamingDataWidthConverter_Batch_24/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingFCLayer_Batch_9/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingFCLayer_Batch_9/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataWidthConverter_Batch_24/out_V] [get_bd_intf_pins StreamingFCLayer_Batch_9/in0_V]
make_bd_intf_pins_external [get_bd_intf_pins StreamingFIFO_0/in0_V]
set_property name s_axis_0 [get_bd_intf_ports in0_V_0]
make_bd_intf_pins_external [get_bd_intf_pins StreamingFCLayer_Batch_9/out_V]
set_property name m_axis_0 [get_bd_intf_ports out_V_0]
set_property CONFIG.FREQ_HZ 100000000.000000 [get_bd_ports /ap_clk]
regenerate_bd_layout
validate_bd_design
save_bd_design
# make_wrapper -files [get_files /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/vivado_stitch_proj_or5_fmik/finn_vivado_stitch_proj.srcs/sources_1/bd/finn_design/finn_design.bd] -top
# add_files -norecurse /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/vivado_stitch_proj_or5_fmik/finn_vivado_stitch_proj.srcs/sources_1/bd/finn_design/hdl/finn_design_wrapper.v
# ipx::package_project -root_dir /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/vivado_stitch_proj_or5_fmik/ip -vendor xilinx_finn -library finn -taxonomy /UserIP -module finn_design -import_files
# set_property core_revision 2 [ipx::find_open_core xilinx_finn:finn:finn_design:1.0]
# ipx::create_xgui_files [ipx::find_open_core xilinx_finn:finn:finn_design:1.0]
# set_property value_resolve_type user [ipx::get_bus_parameters -of [ipx::get_bus_interfaces -of [ipx::current_core ]]]
# ipx::update_checksums [ipx::find_open_core xilinx_finn:finn:finn_design:1.0]
# ipx::save_core [ipx::find_open_core xilinx_finn:finn:finn_design:1.0]
# set all_v_files [get_files -filter {FILE_TYPE == Verilog && USED_IN_SYNTHESIS == 1} ]
# set fp [open /home/nm/FINN/hls_2020_2/finn/notebooks/end2end_example/cnv_w1a1_resize_regression_V5_surgery/stitched_ip_vivado_proj/vivado_stitch_proj_or5_fmik/collected_src_files/src_ips/vivado_stitch_proj_or5_fmik/all_verilog_srcs.txt w]
# foreach vf $all_v_files {puts $fp $vf}
# close $fp
group_bd_cells finn_ip [get_bd_cells StreamingFIFO_0] [get_bd_cells Thresholding_Batch_0] [get_bd_cells StreamingFIFO_1] [get_bd_cells FMPadding_Batch_0] [get_bd_cells StreamingDataWidthConverter_Batch_0] [get_bd_cells StreamingFIFO_3] [get_bd_cells ConvolutionInputGenerator_0] [get_bd_cells StreamingFCLayer_Batch_0] [get_bd_cells StreamingFIFO_5] [get_bd_cells StreamingMaxPool_Batch_0] [get_bd_cells StreamingFIFO_6] [get_bd_cells StreamingDataWidthConverter_Batch_1] [get_bd_cells StreamingFIFO_7] [get_bd_cells FMPadding_Batch_1] [get_bd_cells StreamingDataWidthConverter_Batch_2] [get_bd_cells StreamingFIFO_9] [get_bd_cells ConvolutionInputGenerator_1] [get_bd_cells StreamingDataWidthConverter_Batch_3] [get_bd_cells StreamingFIFO_11] [get_bd_cells StreamingFCLayer_Batch_1] [get_bd_cells StreamingDataWidthConverter_Batch_4] [get_bd_cells StreamingMaxPool_Batch_1] [get_bd_cells StreamingFIFO_14] [get_bd_cells StreamingDataWidthConverter_Batch_5] [get_bd_cells StreamingFIFO_15] [get_bd_cells FMPadding_Batch_2] [get_bd_cells StreamingDataWidthConverter_Batch_6] [get_bd_cells StreamingFIFO_17] [get_bd_cells ConvolutionInputGenerator_2] [get_bd_cells StreamingDataWidthConverter_Batch_7] [get_bd_cells StreamingFIFO_19] [get_bd_cells StreamingFCLayer_Batch_2] [get_bd_cells StreamingDataWidthConverter_Batch_8] [get_bd_cells StreamingMaxPool_Batch_2] [get_bd_cells StreamingFIFO_22] [get_bd_cells StreamingDataWidthConverter_Batch_9] [get_bd_cells StreamingFIFO_23] [get_bd_cells FMPadding_Batch_3] [get_bd_cells StreamingDataWidthConverter_Batch_10] [get_bd_cells StreamingFIFO_25] [get_bd_cells ConvolutionInputGenerator_3] [get_bd_cells StreamingDataWidthConverter_Batch_11] [get_bd_cells StreamingFIFO_27] [get_bd_cells StreamingFCLayer_Batch_3] [get_bd_cells StreamingDataWidthConverter_Batch_12] [get_bd_cells StreamingMaxPool_Batch_3] [get_bd_cells StreamingFIFO_30] [get_bd_cells StreamingDataWidthConverter_Batch_13] [get_bd_cells StreamingFIFO_31] [get_bd_cells FMPadding_Batch_4] [get_bd_cells StreamingFIFO_32] [get_bd_cells ConvolutionInputGenerator_4] [get_bd_cells StreamingDataWidthConverter_Batch_14] [get_bd_cells StreamingFIFO_34] [get_bd_cells StreamingFCLayer_Batch_4] [get_bd_cells StreamingDataWidthConverter_Batch_15] [get_bd_cells StreamingMaxPool_Batch_4] [get_bd_cells StreamingFIFO_37] [get_bd_cells StreamingDataWidthConverter_Batch_16] [get_bd_cells StreamingFIFO_38] [get_bd_cells FMPadding_Batch_5] [get_bd_cells StreamingFIFO_39] [get_bd_cells ConvolutionInputGenerator_5] [get_bd_cells StreamingDataWidthConverter_Batch_17] [get_bd_cells StreamingFIFO_41] [get_bd_cells StreamingFCLayer_Batch_5] [get_bd_cells StreamingDataWidthConverter_Batch_18] [get_bd_cells StreamingMaxPool_Batch_5] [get_bd_cells StreamingDataWidthConverter_Batch_19] [get_bd_cells StreamingFIFO_45] [get_bd_cells FMPadding_Batch_6] [get_bd_cells StreamingFIFO_46] [get_bd_cells ConvolutionInputGenerator_6] [get_bd_cells StreamingDataWidthConverter_Batch_20] [get_bd_cells StreamingFIFO_48] [get_bd_cells StreamingFCLayer_Batch_6] [get_bd_cells StreamingDataWidthConverter_Batch_21] [get_bd_cells StreamingMaxPool_Batch_6] [get_bd_cells StreamingDataWidthConverter_Batch_22] [get_bd_cells StreamingFCLayer_Batch_7] [get_bd_cells StreamingDataWidthConverter_Batch_23] [get_bd_cells StreamingFCLayer_Batch_8] [get_bd_cells StreamingDataWidthConverter_Batch_24] [get_bd_cells StreamingFCLayer_Batch_9] 
regenerate_bd_layout
save_bd_design